### ISSUE TITLE
프로젝트 초기 생성

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#1]
### ✨ Describe

프로젝트 스켈레톤을 구성하고 기본적인 CI/CD를 세팅합니다.

### ✅ Tasks

- [x] AWS 구성 (EC2 프리티어 t2.micro(1cpu, 1gib mem) - linux ubuntu 22.04)
- [x] 원격서버->로컬디비 붙이기
- [x] 로컬에 도커로 Master, Slave 구성
- [x] 서버에 Docker 설치 
- [x] CI workflow 작성 (github actions 사용)
- [x] CD workflow 작성 (github actions 사용)
- [x] 초기 프로젝트 구성 (JDK 21, ~~멀티모듈~~ )
- [x] issue,pr template 구성
