### ISSUE TITLE
페이징 API를 개선해본다

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#12]
### ✨ Describe

현재 TPS 4.3으로 매우 낮은 상태.
먼저, 쿼리 EXPLAIN 부터 살펴보고 인덱스를 걸어 개선 시켜보자.

`API: "http://xxx:8080/api/v1/books?page=1&size=10&sortType=PAGE_COUNT"`

### ✅ Tasks

- [x] 아무 개선을 안했을 때, 쿼리 EXPLAIN 확인 
- [x] querydsl로 no-offset 구현
- [x] 배포 후 TPS 다시 확인해보기 
- [x] 다른 개선 방향

**Comment by minsang-alt** [comment]
### 아무 개선안했을 때
1. 현재 쿼리문 2개 날라갑니다.
```sql
select
        b1_0.book_id,
        b1_0.book_code,
        b1_0.created_at,
        b1_0.book_name,
        b1_0.page_count,
        b1_0.updated_at 
    from
        book b1_0 
    order by
        b1_0.created_at desc 
    limit
        10, 10;

select
        count(b1_0.book_id) 
    from
        book b1_0;
```

![image](https://github.com/user-attachments/assets/668cf0f6-d9a6-4b55-b217-76f74e326034)

첫번째 쿼리
- 테이블 풀 스캔으로 모든 로우를 읽은 상태 
- 인덱스 NULL
- extra 정렬사용 
- duration: 1.379898

**Comment by minsang-alt** [comment]
### 개선 방향 1

- MySQL Explain 결과에서 일반적으로 데이터가 많은 경우 Using Filesort 와 Using Temporary 상태는 좋지 않습니다.
- **filesort가 안좋은 이유**
  - `filesort`가 필요한 상황이 발생하면, MySQL에선 내부적으로 테이블을 `Sort Buffer`에 옮겨 정렬하는 작업을 거친다.
  - 정렬이 완료된 후, 결합이 필요한 데이터가 있다면 합치는 작업을 거친 후 데이터를 내려줄 것이다. (물론 단일 테이블인 경우엔 그대로 내려준다)

**개선 방법**

1. **인덱스 생성**: `created_at` 컬럼에 인덱스를 생성
`CREATE INDEX idx_created_at ON book (created_at DESC);`
![image](https://github.com/user-attachments/assets/356c84ad-5f79-42fb-9b5a-dbf9ad916ec7)

     - 이제 인덱스를 타고 row도 역시나 상위 10 + 10개까지만 확인합니다.
     - duration: 0.0004925
     - desc이 아닌 asc로 쿼리를 바꿔도 extra에 Backward index scan 이 뜨고 빠릅니다.
     - 단점은 page_count, book_name도 정렬을 하기 때문에 이에 대한 인덱스 생성도 따로 생성해야 합니다
     - 300만이 offset이면 duration이 2.60931625로 대폭 느려집니다. -> 옵티마이저가 filesort로 행동합니다

2. **커버링 인덱스 사용**: 모든 필요한 컬럼을 포함하는 복합 인덱스를 생성합니다. 많은 행 조회가 필요하고 반복적이며 칼럼 수정이 딱히 없으면 효과적일것으로 판단 
`CREATE INDEX idx_book_cover ON book (created_at DESC, book_id, book_code, book_name, page_count, updated_at);`
![image](https://github.com/user-attachments/assets/f8ba9283-6550-49bd-a1ca-37a0b13abca5)
     - 커버링 인덱스라 이제 테이블 데이터에 접근하지않으므로 매우 효율적
     - duration: 0.00032525
     - 단점: 
     - 인덱스 크기 증가. 디스크 공간을 더 많이 사용하게 되며, 메모리 사용량도 증가
     - 포함된 컬럼의 데이터가 변경될 때마다 인덱스를 업데이트해야 합니다, 이로 인해 INSERT, UPDATE, DELETE 작업의 성능이 저하될 수 있습니다.

**Comment by minsang-alt** [comment]
### 개선방향 2
참고: 
https://binux.tistory.com/148
https://taegyunwoo.github.io/tech/Tech_DBPagination

쿼리문을 보면 offset은 성능상 좋지 않다고 합니다. 왜냐하면, offset을 사용하는 것은 앞서 많은 행을 읽어들여오고, 이후에 삭제하는 과정을 거칩니다. 즉, offset은 데이터베이스에서 쿼리의 처음 N개 결과를 건너뛰도록 설정한다. 하지만 데이터베이스는 N개 결과 이후의 row만 받아오는 것이 아니라 모든 row를 디스크로부터 읽어오고, N개의 결과까지 순서대로 진행하며 넘기게 되는 식으로 진행됩니다.

즉, 이 쿼리를 실행하면 offset이 300만, row_count 10개 이므로 duration이 2.9174735 초 나왔습니다. (커버링 인덱스 사용하면, 0.57920675로 개선)

```sql
SET profiling = 1;
select
        b1_0.book_id,
        b1_0.book_code,
        b1_0.created_at,
        b1_0.book_name,
        b1_0.page_count,
        b1_0.updated_at
    from
        book b1_0
    order by
        b1_0.created_at desc
    limit
        3000000, 10;
SHOW PROFILES;
```

keyset pagination 방식으로 성능개선이 가능합니다. 하지만, 특정페이지 방문 못한다는 점이 있습니다.(무한스크롤만 가능)

1. **NO-OFFSET 방식으로 성능 개선** (OFFSET 대신 WHERE 을 사용)
    - No Offset으로 구조를 변경 (No Offset은 아래와 같이 페이지 번호 (offset)가 없는 더보기 (More) 방식을 이야기 합니다.)
    - 조건절 칼럼은 인덱스 적용 필수
    - `CREATE INDEX idx_created_at ON book (created_at DESC);`
    - `SELECT * FROM BOOK WHERE created_at <= '2022-05-31 21:43:43.712214' ORDER BY created_at desc LIMIT 10;`
    -  duration: 0.00044925
    
![image](https://github.com/user-attachments/assets/7b17bcfd-d071-4536-bf58-2808f08b82f3)

이제 offset방식이 아니라서 바로 조건절에 있는 `2022-05-31 21:43:43.712214`로 건너띈다음 읽기 시작합니다. 이는 인덱스 풀 스캔이 아닌 인덱스 레인지 스캔으로 동작한다고 볼 수 있습니다.

### 여기까지 내린 결론
단순 인덱스를 거는 것은 offset의 단점 때문에 성능 개선이 불가능합니다. 그래서 이를 해결할 수 있는 2가지 방식은 커버링 인덱스와 NO-OFFSET 방식이 있습니다.

먼저, 커버링 인덱스는 많은 인덱스를 생성해야 하는 점, 앞으로 칼럼이 추가될 가능성도 배제할 수 없기 때문에 인덱스를 업데이트 할 수 있다는 점과 많은 인덱스는 또 INSERT 등 쿼리 성능에 저하될 수 있다는 단점때문에 NO-OFFSET 방식으로 성능을 개선해야 겠습니다. 

이를 위해서 QueryDSL 추가
