### ISSUE TITLE
페이지네이션 책 검색 API OFFSET 방식으로 성능 개선해본다

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#14]
### ✨ Describe

저번에는 NO-OFFSET 방식으로 해결했지만, 무한 스크롤이 아닌 페이지번호 방식의 클라이언트에서는 사용이 불가능합니다.
따라서 여기에서도 성능개선이 필요합니다.

### ✅ Tasks

- [x] 책 검색 API도 페이지네이션으로 변경 
- [x] 커버링 인덱스 단점 
- [x] OFFSET 방식 개선 
- [x] 카운트 쿼리 성능 개선 
- [x] 페이지네이션 적용 후, 카운트 쿼리 개선 전 TPS 확인 필요 
- [x] 페이지네이션 적용 및 카운트 쿼리 개선 후 TPS 확인 필요 
- [x] 블로그 작성

**Comment by minsang-alt** [comment]
```
select
        count(b1_0.book_id)
    from
        book b1_0
    where
        b1_0.book_name like '%2%'
    and
        b1_0.page_count < 300;
```

조건절에 여러개의 조건이 있을 경우 성능이 급격히 안좋아진다.
duration: 5.364초
![image](https://github.com/user-attachments/assets/7811131e-e738-418b-8682-c42aa03e0937)
- page_count, book_name 모두 인덱스를 생성한 상태에도 불구하고, 테이블 풀 스캔을 한다. 

만약 조건이 하나이면
```
explain
select
        count(b1_0.book_id)
    from
        book b1_0
    where
        b1_0.book_name like '%2%';
```
![image](https://github.com/user-attachments/assets/6a7752c6-21d0-470e-b47a-183fc02c98a1)

- 인덱스 풀 스캔 + 커버링 인덱스로 duration이 0.9초

**Comment by minsang-alt** [comment]
이유파악 ( EXPLAIN ANALYZE 결과를 해석해보자)
---
```
-> Aggregate: count(b1_0.book_id)  (cost=532835 rows=1) (actual time=1711..1711 rows=1 loops=1)
    -> Filter: ((b1_0.book_name like '%2%') and (b1_0.page_count < 300))  (cost=505839 rows=269956) (actual time=0.446..1691 rows=755403 loops=1)
        -> Table scan on b1_0  (cost=505839 rows=4.86e+6) (actual time=0.314..1055 rows=5e+6 loops=1)
```
해석해보면 
Table scan on b1_0: 전체 테이블을 스캔합니다
Filter: ((b1_0.book_name like '%2%') and (b1_0.page_count < 300)): 테이블 스캔 후 두 조건으로 필터링합니다.
Aggregate: count(b1_0.book_id): 마지막으로 필터링된 행의 수를 집계합니다.

문제점 
---

1. 인덱스를 사용하지 않고 전체 테이블 스캔
2. 필터링이 데이터를 읽은 후에 이루어진다


TPS 테스트
---
`"http://175.45.205.48:8080/api/v1/books/search?page=3&size=30&bookCode=A&name=2&minPageCount=30&maxPageCount=500"`

![image](https://github.com/user-attachments/assets/43107564-08bf-4905-bb1d-b78e3aac774a)

**Comment by minsang-alt** [comment]
커버링 인덱스 사용
---
1. 자주 검색되는 조건을 앞 순위에 넣음
2. 보통 책이름과 페이지 카운트만 검색한다고 가정
3. 실제로 커버링 인덱스를 태우는 부분은 select를 제외한 나머지만 우선으로 수행
4.
```
EXPLAIN
    select
            b1_0.book_id,
            b1_0.book_code,
            b1_0.created_at,
            b1_0.book_name,
            b1_0.page_count,
            b1_0.updated_at
    from
        Book b1_0
    where
        b1_0.book_name like '%4%'
        and b1_0.page_count >= 50
        and b1_0.page_count <= 300
    order by
        b1_0.created_at desc
    limit
        30, 10;

```
5. 초기 인덱스는 다음과 같음
![image](https://github.com/user-attachments/assets/570fa19a-f1bd-48fe-a6ea-77515861cc02)

6. 당연히 EXPLAIN 결과는 테이블 풀 스캔 , duration 5.8s
7. 커버링 인덱스 생성 `CREATE INDEX idx_book_covering_search ON book (book_name, page_count);`
![image](https://github.com/user-attachments/assets/44d53e65-7202-4c33-bc34-bae8d5f59c7e)
8. 다시 EXPLAIN
![image](https://github.com/user-attachments/assets/4191a588-7c24-481d-af47-440c7125496f)
커버링 인덱스 및 인덱스 풀 스캔 , duration 1.05s
9. 5.8s -> 1.05s로 개선 
10. 그리고 like절이 앞에 %라서 극단적으로 성능이 안좋아진다 '4%' 식으로 검색하면 0.0008125초로 더 줄어든다.
11. 이건 쿼리를 수정하면 된다 page_count를 먼저 검색하고, 거기서 나온 로우로 like절 검색
12. 1.05s -> 0.69781825s로 좀 개선됨 하지만, page_count가 >= 만 조건처리되면 다시 1초대로 복구. 읽는 로우수가 많아져서 그렇다.
```
SELECT COUNT(*)
FROM Book book
WHERE book.page_count BETWEEN 50 AND 300
  AND book.book_name LIKE '%4%';
```
13. 참고로 카운트 쿼리말고, OFFSET 페이징은 여전히 `Index scan on b1_0 using idx_created_a`으로 다른 인덱스로 쓰고 있음. 하지만 OFFSET 특징상 앞 페이지는 성능상 문제 없음.
14. 그리고 카운트쿼리는 select 절이 필요가 없어서 (로우 카운트) where절 만으로 쉽게 커버링 인덱스 가능 

커버링 인덱스 단점
---

- 너무 많은 인덱스가 필요하다 : 앞으로 조건절이 추가되면 인덱스가 더 추가될 가능성이 있다. 현재 book_code는 검색할 일이 거의없다고 보아 인덱스 생성안한 상태
- 인덱스 크기가 너무 커진다 
- insert나 update가 일어나면 인덱스테이블도 수정해야하기 때문에 새로운 성능 문제가 발생한다.

TPS 결과
---
![image](https://github.com/user-attachments/assets/634408f1-a1f4-493d-b68e-02328ac72444)

아주 조금 개선되었다.
TPS 5.4 -> 8.8
MTT 1900 -> 1142

데이터베이스에 병목이 발생했나 해서 다시 duration 확인했지만, 첫 페이징 쿼리 0.03s , 카운트쿼리 0.7s 로 그렇게 극단적인 초가 아닌데도 불구하고 여전히 TPS가 낮다. 쿼리 2번 발생이 큰건가?
