### ISSUE TITLE
이메일 초대로 독서 챌린지 참여 시스템을 구현한다 

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#16]
### 비즈니스 시나리오
1. 챌린지 생성자가 다른 사용자들을 이메일로 초대
2. 초대받은 사용자는 이메일의 링크를 통해 챌린지에 즉시 참여
3. 참가자 수 제한 내에서만 초대 가능
4. 초대 링크는 5분 후 만료
5. 챌린지 시작 전에만 초대 가능 

### 요구사항

1. 초대 가능 조건
- [ ] 챌린지 생성자만 초대 가능
- [ ] 챌린지 시작 전에만 초대 가능
- [ ] 챌린지의 참가자 수 제한 확인
- [ ] 한 번에 여러 명 초대 가능

2. 초대 링크/코드

 - [ ] 초대 코드는 UUID로 생성
 - [ ]  Redis에 초대 코드 + 챌린지 ID 저장
 - [ ]  유효시간 5분 설정 (TTL)
 - [ ]  초대 링크 형식: /challenges/invite?code={초대코드}

3. 초대 수락 프로세스

- [ ] 링크 접속 시 초대 코드 유효성 검증
- [ ]  로그인된 사용자만 수락 가능
- [ ]  챌린지 참가 가능 여부 재확인 (시작 전 챌린지인지, 참가자 수 제한 초과하지 않는지)
- [ ] 초대 수락 시 챌린지 참가자로 등록

### ✅ Tasks

- [x] 최소 회원 기능 구현(User 객체와 stateless한 방식인 JWT로 회원 인증)
- [x] Gmail SMTP 설정
- [ ] Redis 연결
- [ ] 챌린지 초대 API 구현 

### 고려해야 할 시나리오

1. 동시에 많은 초대가 발생할 수 있는 상황
- 인기 있는 챌린지에 여러 사람을 한 번에 초대
- 여러 챌린지 호스트가 동시에 초대장 발송
- 대회나 이벤트로 인한 대량 초대
