### ISSUE TITLE
책 조회에 대한 페이징 API를 만들고 조건을 추가한다음 성능측정을 한다 

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#5]
### ✨ Describe

데이터 몇백만건 많이 넣고나서 기본적인 페이징 API를 구현, 다양한 조건(정렬, 필터링)을 추가 하고 JMeter 같은 도구로 성능측정을 합니다

### ✅ Tasks

- [x] db schema 생성
- [x] erd 리뷰 수정
- [x] #4  리뷰 해결
- [x] ~~모든~~ book 테이블에만 500만건 데이터 넣기
- [x] JPA auditing 설정 
- [ ] 애플리케이션 레벨에서 이넘으로 관리할 때 생기는 문제점 찾기 
- [ ] 브랜치 전략 숙지
- [x] 기본적인 페이징 API를 구현
- [x] 다양한 조건(정렬, 필터링)을 추가
- [x] 성능 측정 (Jmeter?) -> nGrinder 이용

**Comment by minsang-alt** [comment]
![image](https://github.com/user-attachments/assets/b7eb3529-7435-4eff-aa8c-985565a5e24c)

**Comment by minsang-alt** [comment]
![image](https://github.com/user-attachments/assets/909127f7-b5e1-47bd-af7a-3068d72a3197)
