### ISSUE TITLE
Logback을 이용해 운영 환경 별 로그를 남긴다

### ISSUE THREAD

**Issue by minsang-alt** [f-lab-edu/book-challenge#9]
### ✨ Describe

어디서 병목이 발생하는 지 확실히 알기 위함과 로그분석과 쿼리 확인을 쉽게 하도록 logback 설정 

### ✅ Tasks

- [x] logback-spring.xml 작성 & 환경 별 로그 작성
- [x] 서버 이전 (ec2 -> Ncloud)
- [x] TPS 다시 확인 

### 🙋🏻 More

```java
<logger name="org.hibernate.SQL" level="DEBUG"/>
<logger name="org.hibernate.type.descriptor.sql.BasicBinder" level="TRACE"/>
```

**Comment by minsang-alt** [comment]
![image](https://github.com/user-attachments/assets/235ecf3b-2532-49cf-9889-06b26fd329c8)

tps 230대로 서버이전(1cpu,1gib -> 2cpu,4GB)해도 딱히 안오름
먼저 페이징 API에 대한 쿼리 Explain 부터 확인해보자
